config/routes.rb
Rails.application.routes.draw do

  get '/grades/new', to: 'grades#new', as: "new_grade"
  post '/grades', to: 'grades#create'
 
  get '/instructors', to: 'instructors#index', as: "instructors"
  get '/instructors/:id', to: 'instructors#show', as: "instructor"

  get '/courses', to: 'courses#index', as: "courses"
  get '/courses/:id', to: 'courses#show', as: "course"

  get '/students', to: 'students#index', as: "students"
  get '/students/new', to: 'students#new', as: "new_student"
  post '/students', to: 'students#create'
  get '/students/:id', to: 'students#show', as: "student"
  get '/students/:id/edit', to: 'students#edit', as: "edit_student"
  patch '/students/:id', to: 'students#update'
  delete '/students/:id', to: 'students#destroy'




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :instructor
  has_many :grades
  has_many :students, through: :grades

  
  validates :seat_limit, numericality: {greater_than_or_equal_to: 0, message: "Not enough seats to register" }
  validates :seat_limit, numericality: {less_than: 11, message: "No More than 10 seats available"}
  
  def status
    if open
        "Open for Enrollment"
    else
        "Closed"
    end
  end



 

  def open_seats
    self.seat_limit - self.grades.count
  end

end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student
  belongs_to :course

 




end

app/models/instructor.rb
class Instructor < ApplicationRecord
    has_many :tutorings
    has_many :courses
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :grades, dependent: :destroy
    has_many :courses, through: :grades

    validates :name, presence: true, uniqueness: true
    validates :age, numericality: {less_than: 80, message: "You're too old!"}
    validates :age, numericality: {greater_than: 20, message: "You're too young!"}
    validates :major, presence: true
end

app/models/tutoring.rb
class Tutoring < ApplicationRecord
  belongs_to :instructor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

    def index
        @courses = Course.all
    end

    def show
        @course = Course.find(params[:id])
    end

    def new 
        @course = Course.new
    end

    def create
        @course = Course.create(course_params)
        redirect_to course_path(@course)
    end

    def update
        @course = Course.find(params[:id])
        @course.update(course_params)
        redirect_to course_path(@course)
    end

    def edit
        @course = Course.find(params[:id])
    end

    def destroy
        @course = Course.find(params[:id])
        @course.destroy 
        redirect_to courses_path
    end

    


    private

    def course_params
        params.require(:course).permit(:name, :seat_limit, :week_day, :time, :instructor_id)
    end

end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
    def index
        @grades = Grade.all
    end

    def show
        @grade = Grade.find(params[:id])
    end

    def new 
        @grade = Grade.new
        @students = Student.all
        @courses = Course.all 
    end

    def create
        course = Course.find(params[:grade][:course_id])
        if course.open_seats > 0 && course.open_seats < 11 
            @grade = Grade.create(grade_params)
            redirect_to student_path(@grade.student_id)
        else
            flash[:errors] = ["Course is full.", "Choose another course."]
            redirect_to new_grade_path
        end
    end

    def update
        @grade = Grade.find(params[:id])
        @grade.update(grade_params)
        redirect_to student_path(@grade.student_id)
    end

    def edit
        @grade = Grade.find(params[:id])
        @student = Student.all
        @course = Course.all
    end

    def destroy
        @grade = Grade.find(params[:id])
        @grade.destroy 
        redirect_to student_path
    end

    private

    def grade_params
        params.require(:grade).permit(:grade_value, :student_id, :course_id)
    end

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

    def index
        @instructors = Instructor.all
    end

    def show
        @instructor = Instructor.find(params[:id])
    end

    def new 
        @instructor = Instructor.new
    end

    def create
        @instructor = Instructor.create(instructor_params)
        redirect_to instructor_path(@instructor)
    end

    def update
        @instructor = Instructor.find(params[:id])
        @instructor.update(instructor_params)
    end

    def edit
        @instructor = Instructor.find(params[:id])
    end

    def destroy
        @instructor = Instructor.find(params[:id])
        @instructor.destroy 
        redirect_to instructors_path
    end

    private

    def instructor_params
        params.require(:instructor).permit(:name)
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    def index
        @students = Student.all
    end

    def show
        @student = Student.find(params[:id])
    end

    def new 
        @student = Student.new
    end

    def create
        @student = Student.create(student_params)
        if @student.valid?
        redirect_to student_path(@student) 
        else
          flash[:errors] = @student.errors.full_messages
          redirect_to new_student_path  
        end
    end

    def update
        @student = Student.find(params[:id])
        if @student.update(student_params)
            redirect_to student_path(@student)
        else
            flash[:errors] = @student.errors.full_messages
            redirect_to edit_student_path(@student)
        end
    end

    def edit
        @student = Student.find(params[:id])
    end

    def destroy
        @student = Student.find(params[:id])
        @student.destroy 
        redirect_to students_path
    end

    private

    def student_params
        params.require(:student).permit(:name, :age, :major)
    end

end

app/controllers/tutorings_controller.rb
class TutoringsController < ApplicationController

    def show
        @tutoring = Tutoring.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/office_hours_helper.rb
module OfficeHoursHelper
end

app/helpers/registrars_helper.rb
module RegistrarsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tutorings_helper.rb
module TutoringsHelper
end

app/views/courses/index.html.erb
<h1> All Courses </h1>

<ol> 
    <% @courses.each do |course| %>
     <li>
        <%= link_to course.name, course_path(course) %>
        <%end%>
    </li>
     
</ol>

<br>
<%= link_to "Back to Students", students_path %>

app/views/courses/show.html.erb
<h1> <%= @course.name %> Information </h1>
<br>
<h3>Seat Limit: <%= @course.seat_limit() %> </h3>
<h3> Open Seats: <%= @course.open_seats %> </h3>
<br>
<h3>Instructor: <%= link_to @course.instructor.name, instructor_path(@course.instructor) %> </h3>
<br>
<h3>Schedule: <%= @course.week_day %> - <%=@course.time %> </h3>
<hr>
<h2> Enrolled Students</h2>
<ol>
    <% @course.grades.each do |course_inst| %>
    <li>
        <%= link_to course_inst.student.name, student_path(course_inst.student) %>
    </li>
    <% end %>
</ol>
<br>
<%= link_to "Back to Courses", courses_path %>
<br>
<%= link_to "Enroll in a Course", new_grade_path%>

app/views/grades/edit.html.erb
<h1> Edit <%= @grade.student.name %>'s Grade </h1>

<%= form_for @grade do |f| %>
    <%= f.label :student_id %>
    <%= f.collection_select :student_id, @student, :id, :name %>
    <%= f.label :course_id %>
    <%= f.collection_select :course_id, @course, :id, :name %>
    <%= f.label :grade_value %>
    <%= f.collection_select :grade_value, (1..10).to_a, :itself, :itself %>
    <%= f.submit %>
<% end %>
<br>
<%= button_to "Delete Grade", grade_path(@grade), method: "delete" %>
<br>
<%= link_to "Back to Students", students_path %>
<br>
<%= link_to "Back to Courses", courses_path %>

app/views/grades/new.html.erb
<h1> Enroll in Course </h1>

<% if flash[:errors]%>
    <ul>
        <% flash[:errors].each do |error|%>
        <li>
            <%= error %>
        </li>
         <% end %>
    </ul>
<%end%>

<%= form_for @grade do |f| %>
    <%= f.label :student_id %>
    <%= f.collection_select :student_id, @students, :id, :name %>
    <%= f.label :course_id %>
    <%= f.collection_select :course_id, @courses, :id, :name %>
    <%# <%= f.label :grade_value %>
    <%# <%= f.collection_select :grade_value, (1..10).to_a, :itself, :itself %>
    <%= f.submit "Enroll"%>
<% end %>

<br>
<%= link_to "Back to Courses", courses_path %>

app/views/instructors/index.html.erb
<h1> All Instructors </h1>

<ol> 
    <% @instructors.each do |instructor| %>
     <li>
        <%= link_to instructor.name, instructor_path(instructor) %>
        <%end%>
    </li>
     
</ol>

app/views/instructors/show.html.erb
<h1> Instructor Information </h1>

<h3> <%= @instructor.name %> </h3> 

<hr>
<h4> <p>  Courses </p> </h4>

<ul>
    <% @instructor.courses.each do |instructor_inst| %>
        <li> <%= link_to instructor_inst.name, course_path(instructor_inst) %>  </li>
    <%end%>

</ul>

<h2> Tutoring Schedule</h2>
<hr>
    <% @instructor.tutorings.each do |tutor|%>
        <h3> <%= tutor.week_day %> at <%= tutor.time %> </h3>
    <% end %>
<br>
<hr>
<br>
<%= link_to "Back to Instructors", instructors_path %>
<br>
<%= link_to "Back to Students", students_path %>
<br>
<%= link_to "Back to Courses", courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RetakeUniversity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1> Edit <%= @student.name %> </h1>
<% if flash[:errors]%>
    <ul>
        <% flash[:errors].each do |error|%>
        <li>
            <%= error %>
        </li>
         <%end%>
    </ul>
<%end%>

<%= form_for @student do |f| %>
    <%= f.label :name, "Name"%>
    <%= f.text_field :name %>
    <%= f.label :age, "Age"%>
    <%= f.number_field :age %>
    <%= f.label :major, "Major" %>
        <%= f.text_field :major %>
<%= f.submit "Edit Student" %>

<% end %>

<br>
<%= link_to "Back to Courses", courses_path %>

app/views/students/index.html.erb
<h1> All Students </h1>

<ol> 
    <% @students.each do |student| %>
     <li>
        <%= link_to student.name, student_path(student) %>
        <%end%>
    </li>
     
</ol>

<br>
<%= link_to "Back to Courses", courses_path %>
<br>
<%= link_to "Create a New Student", new_student_path %>

app/views/students/new.html.erb
<h1> Student Form</h1>

<% if flash[:errors]%>
    <ul>
        <% flash[:errors].each do |error|%>
        <li>
            <%= error %>
        </li>
         <%end%>
    </ul>
<%end%>


<%= form_for @student do |f| %>
    <%= f.label :name, "Name"%>
    <%= f.text_field :name %>
    <%= f.label :age, "Age"%>
    <%= f.number_field :age %>
    <%= f.label :major, "Major" %>
    <%= f.text_field :major %>
    <%= f.submit %>
<% end %>

<br>
<%= link_to "Back to Courses", courses_path %>
<br>
<%= link_to "Back to All Students", students_path %>

app/views/students/show.html.erb
<h1> <%= @student.name %> </h1>

<h2> Major - <%= @student.major %> </h2>
<h2> Age - <%= @student.age %> </h2>

<hr> 

<h1> Course Grades </h1> 

<ol> 
    <% @student.grades.each do |grade_inst| %>
    <li> 
        <%= link_to grade_inst.course.name, course_path(grade_inst.course) %> - <%= grade_inst.grade_value%>
    </li>
    <% end %>
</ol>

<hr> 


<br>
<%= link_to "Edit Student", edit_student_path %>
<br>
<%= link_to "Back to Students", students_path %>
<br>
<%= link_to "Enroll in a Course", new_grade_path%>
<br>
<%= link_to "Go to Courses", courses_path %>
<br>
<%= button_to "Delete Student", student_path(@student), method: "delete" %>